services:
  echoserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: scheibling/simple-echo-server:latest
    ports:
      - "8080:8080"
    environment:
      ECHO_STRING: "Hello, World!\r\n"
      LISTEN_PORT: "8080"
  
      